tap "dashlane/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
brew "automake"
brew "bison"
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "glib"
brew "chruby"
brew "gmp"
brew "coreutils"
brew "docker"
brew "gdbm"
brew "gh"
brew "git"
brew "git-gui"
brew "gnupg"
brew "gnupg@2.2"
brew "go"
brew "ical-buddy"
brew "shared-mime-info"
brew "libtool"
brew "libffi", link: true
brew "libxmlsec1"
brew "libyaml"
brew "llm"
brew "mas"
brew "mysql", restart_service: true
brew "pkg-config"
brew "node-build"
brew "openssl@1.1"
brew "node@14"
brew "nodenv"
brew "nvm"
brew "opensearch", restart_service: true
brew "postgresql@14", restart_service: true
brew "pyenv"
brew "rbenv"
brew "redis", restart_service: true
brew "ruby-install"
brew "rust"
brew "tree"
brew "vips"
brew "wget"
brew "yarn"
brew "zsh"
brew "dashlane/tap/dashlane-cli"
brew "heroku/brew/heroku"
cask "alchemy"
cask "aldente"
cask "arc"
cask "authy"
cask "cheatsheet"
cask "datagrip"
cask "dbeaver-community"
cask "discord"
cask "duckduckgo"
cask "fig"
cask "firefox"
cask "font-anonymous-pro"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-for-powerline"
cask "font-fira-mono-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-intel-one-mono"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "google-chrome"
cask "google-drive"
cask "intellij-idea"
cask "istat-menus"
cask "kindle"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mullvadvpn"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "oracle-jdk"
cask "orion"
cask "pieces"
cask "pieces-os"
cask "postico"
cask "postman"
cask "raindropio"
cask "raycast"
cask "rectangle"
cask "rubymine"
cask "shottr"
cask "signal"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "webstorm"
cask "whatsapp"
cask "zed"
cask "zoom"
mas "2FAS - Two Factor Authentication Extension", id: 6443941139
mas "Aiko", id: 1672085276
mas "Amazing AI", id: 1660147028
mas "Bandwidth+", id: 490461369
mas "Budget Flow", id: 1640091876
mas "Dashlane", id: 517914548
mas "Hand Mirror", id: 1502839586
mas "Hidden Bar", id: 1452453066
mas "iStat Menus", id: 1319778037
mas "Keynote", id: 409183694
mas "Menu Bar Calendar", id: 1558360383
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "reMarkable", id: 1276493162
mas "Save to Pocket", id: 1477385213
mas "Save to Raindrop.io", id: 1549370672
mas "TextSniper", id: 1528890965
mas "Tot", id: 1491071483
vscode "aaron-bond.better-comments"
vscode "adpyke.codesnap"
vscode "alefragnani.bookmarks"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "batatop.terminal-auto-rename"
vscode "bung87.rails"
vscode "bung87.vscode-gemfile"
vscode "castwide.solargraph"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "chrmarti.regex"
vscode "danielsanmedium.dscodegpt"
vscode "davidanson.vscode-markdownlint"
vscode "davidpallinder.rails-test-runner"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "int-tt.vscode-sops"
vscode "ionutvmi.path-autocomplete"
vscode "jakebecker.elixir-ls"
vscode "kaiwood.endwise"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "kohkimakimoto.vscode-mac-dictionary"
vscode "koichisasada.vscode-rdbg"
vscode "lokalise.i18n-ally"
vscode "mechatroner.rainbow-csv"
vscode "meshintelligenttechnologiesinc.pieces-vscode"
vscode "mgmcdermott.vscode-language-babel"
vscode "mikestead.dotenv"
vscode "mintlify.document"
vscode "misogi.ruby-rubocop"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.vscode-typescript-next"
vscode "naumovs.color-highlight"
vscode "oderwat.indent-rainbow"
vscode "patbenatar.advanced-new-file"
vscode "pkief.material-icon-theme"
vscode "pranaygp.vscode-css-peek"
vscode "redhat.vscode-yaml"
vscode "riey.erb"
vscode "ritwickdey.liveserver"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "shopify.ruby-extensions-pack"
vscode "shopify.ruby-lsp"
vscode "sianglim.slim"
vscode "sorbet.sorbet-vscode-extension"
vscode "sourcegraph.cody-ai"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "swellaby.rust-pack"
vscode "switchcase.code-challenging-timer"
vscode "tamasfe.even-better-toml"
vscode "ue.alphabetical-sorter"
vscode "usernamehw.errorlens"
vscode "vortizhe.simple-ruby-erb"
vscode "wayou.vscode-todo-highlight"
vscode "wmaurer.change-case"
vscode "xabikos.javascriptsnippets"
vscode "yzhang.markdown-all-in-one"
vscode "zh9528.file-size"
